export type Category='CS2'|'Gry'|'Samochody'|'Jedzenie'|'Zwierzęta'|'Codzienne'|'Internet'|'Losowe'|'Sport'|'Kreatywne'|'Muzyka'|'Filmy i seriale'|'Podróże'|'Szkoła i praca'|'Technologia';
export type CategoryFilter=Category|'Wszystkie';
export interface QuestionPair{id:number;questionA:string;questionB:string;category:Category;hintA?:string;hintB?:string}
const pairs:Array<[Category,string,string,string?,string?]>=[
['CS2','Jaki typ zagrania daje ci największą satysfakcję?','Jaki błąd drużyny najbardziej cię denerwuje?'],['CS2','Jaką broń kupujesz najczęściej?','Jaką broń najczęściej podnosisz po przeciwniku?'],['CS2','Ile fragów to dla ciebie dobry mecz?','Ile fragów zwykle robisz?'],['CS2','Którą mapę znasz najlepiej?','Na której mapie najczęściej się gubisz?'],['CS2','Jaka broń najlepiej wygląda?','Jaka broń najlepiej brzmi?'],
['CS2','Na którym bombsite wolisz grać?','Którego bombsite najtrudniej ci odbić?'],['CS2','Którą pozycję najczęściej zajmujesz?','Której pozycji najbardziej nie lubisz pilnować?'],['CS2','Jaki granat kupujesz najczęściej?','O jakim granacie najczęściej zapominasz?'],['CS2','Z kim najlepiej gra ci się w drużynie?','Kto najbardziej rozprasza cię podczas gry?'],['CS2','Jaki skin chciałbyś mieć?','Jaki skin sprzedałbyś jako pierwszy?'],
['CS2','Ile rund przewagi daje ci spokój?','Przy ilu rundach straty tracisz nadzieję?'],['CS2','Który pistolet wybierasz?','Z którym pistoletem radzisz sobie najgorzej?'],['CS2','Jakiego pro gracza oglądasz najchętniej?','Z jakim pro graczem chciałbyś zagrać?'],['CS2','Co kupujesz po wygranej pistoletówce?','Co kupujesz, gdy brakuje pieniędzy?'],['CS2','Jaką rolę lubisz grać?','Jakiej roli unikasz?'],
['CS2','Gdzie najczęściej rzucasz smoke?','Gdzie najbardziej przeszkadza ci smoke?'],['CS2','Jaki wynik uznajesz za bliski?','Przy jakim wyniku mecz jest już przegrany?'],['CS2','Ile godzin tygodniowo grasz?','Ile godzin tygodniowo oglądasz CS2?'],['CS2','Która mapa ma najlepszy klimat?','Która mapa ma najgorszą widoczność?'],['CS2','Jaką broń wybierasz na daleki dystans?','Jaką broń wybierasz na bliski dystans?'],
['CS2','Kiedy najczęściej robisz eco?','Kiedy najczęściej robisz force buy?'],['CS2','Co najczęściej krzyczysz po wygranej?','Co robisz po przegranej rundzie?'],['CS2','Jaki nóż chciałbyś wylosować?','Jakiego noża nie chciałbyś dostać?'],['CS2','Ile czasu potrzebujesz na rozgrzewkę?','Po ilu meczach robisz przerwę?'],['CS2','Który tryb gry wybierasz najczęściej?','Którego trybu prawie nie używasz?'],
['CS2','Co najlepiej poprawia twoją celność?','Co najbardziej psuje twoją celność?'],['CS2','Na której mapie najlepiej grasz jako CT?','Na której mapie najlepiej grasz jako T?'],['CS2','Jaki nick zapamiętałeś najbardziej?','Jaki nick ustawiłbyś sobie dziś?'],['CS2','Który dźwięk w grze rozpoznajesz od razu?','Który dźwięk najczęściej ignorujesz?'],['CS2','Co robisz przed meczem rankingowym?','Co robisz zaraz po meczu rankingowym?'],
['Gry','Który boss z gry zapadł ci w pamięć?','Który poziom z gry zapadł ci w pamięć?'],['Gry','Jaka gra była twoją pierwszą?','Jaką grę ostatnio uruchomiłeś?'],['Gry','Która postać z gry jest najlepsza?','Która postać z gry najbardziej cię denerwuje?'],['Gry','Na jakiej konsoli chciałbyś grać?','Jaką konsolę miałeś jako pierwszą?'],['Gry','Jaka gra najlepiej nadaje się na imprezę?','Jaka gra najlepiej nadaje się do grania samemu?'],
['Samochody','Jakim autem chciałbyś jeździć na co dzień?','Jakim autem chciałbyś przejechać się tylko raz?'],['Samochody','Jaki kolor auta wybrałbyś dla siebie?','Jaki kolor auta najłatwiej zauważyć?'],['Samochody','Jaka marka wygląda najlepiej?','Jaka marka jest najbardziej praktyczna?'],['Samochody','Ile powinno kosztować dobre auto?','Ile wydałbyś na pierwsze auto?'],['Samochody','Gdzie pojechałbyś samochodem?','Gdzie nigdy nie chciałbyś prowadzić?'],
['Jedzenie','Jakie jedzenie zamawiasz najczęściej?','Jakie jedzenie najchętniej przygotowałbyś sam?'],['Jedzenie','Co najlepiej jeść rano?','Co najlepiej jeść późnym wieczorem?'],['Jedzenie','Jaki smak lodów wybierasz?','Jakiego smaku lodów nigdy nie wybierasz?'],['Jedzenie','Co kupujesz na imprezę?','Co zabierasz na piknik?'],['Jedzenie','Jaka potrawa kojarzy ci się z domem?','Jaką potrawę chciałbyś spróbować za granicą?'],
['Zwierzęta','Jakim zwierzęciem chciałbyś być?','Jakie zwierzę najbardziej cię wkurza?'],['Zwierzęta','Jakie zwierzę jest najsłodsze?','Jakie zwierzę jest najstraszniejsze?'],['Zwierzęta','Które zwierzę najlepiej radzi sobie nocą?','Które zwierzę najlepiej radzi sobie w dzień?'],['Zwierzęta','Które zwierzę najlepiej pływa?','Które zwierzę najlepiej biega?'],['Zwierzęta','Jakie zwierzę kojarzy ci się z tobą?','Jakie zwierzę kojarzy ci się z twoim sąsiadem?'],
['Codzienne','O której zwykle wstajesz?','O której zwykle zasypiasz?'],['Codzienne','Co robisz zaraz po obudzeniu?','Co robisz tuż przed snem?'],['Codzienne','Ile czasu zajmuje ci wyjście z domu?','Ile czasu zajmuje ci powrót do formy po imprezie?'],['Codzienne','Co najczęściej nosisz w kieszeni?','Co najczęściej zostawiasz w domu?'],['Codzienne','Gdzie odpoczywasz najlepiej?','Gdzie najłatwiej ci zasnąć?'],
['Internet','Jakiej aplikacji używasz najczęściej?','Którą aplikację najchętniej byś usunął?'],['Internet','Kogo najchętniej oglądasz w internecie?','Z kim chciałbyś nagrać film?'],['Internet','Jaki mem zawsze cię śmieszy?','Jaki mem znudził ci się najbardziej?'],['Internet','Ile czasu spędzasz dziennie online?','Ile czasu wytrzymasz bez internetu?'],['Internet','Co najczęściej wyszukujesz?','Czego nigdy nie wpisałbyś publicznie?'],
['Losowe','Co zabrałbyś na bezludną wyspę?','Co zabrałbyś na koniec świata?'],['Losowe','Jaki superpower chciałbyś mieć?','Jaki superpower byłby najbardziej bezużyteczny?'],['Losowe','Gdzie chciałbyś mieszkać?','Gdzie chciałbyś pojechać tylko raz?'],['Losowe','Co kupiłbyś za milion złotych?','Co kupiłbyś za ostatnie sto złotych?'],['Losowe','Kim chciałeś zostać jako dziecko?','Kim chciałbyś być przez jeden dzień?'],
['Kreatywne','Narysuj pojazd z przyszłości.','Narysuj dom z przyszłości.','Pomyśl o niezwykłym napędzie, kołach albo skrzydłach.','Dodaj element, którego nie ma w dzisiejszych domach.'],
['Kreatywne','Narysuj nowe zwierzę.','Narysuj nową roślinę.','Połącz cechy dwóch znanych zwierząt.','Wymyśl kształt, liście lub owoce, których jeszcze nie ma.'],
['Kreatywne','Narysuj robota do sprzątania.','Narysuj robota do gotowania.','Pokaż narzędzie, którym robot usuwa bałagan.','Pokaż, jak robot przygotowuje albo podaje jedzenie.'],
['Kreatywne','Narysuj najdziwniejszy plac zabaw.','Narysuj najdziwniejszą szkołę.','Zmień huśtawkę, zjeżdżalnię lub karuzelę.','Zmień salę lekcyjną, ławki albo tablicę.'],
['Kreatywne','Narysuj superbohatera z zabawną mocą.','Narysuj złoczyńcę z zabawną mocą.','Pokaż moc za pomocą stroju lub rekwizytu.','Pokaż, czym postać próbuje przeszkodzić innym.'],
['Kreatywne','Narysuj wyspę marzeń.','Narysuj planetę marzeń.','Dodaj miejsce do odpoczynku i jedną atrakcję.','Pokaż nietypowy krajobraz albo mieszkańców.'],
['Kreatywne','Narysuj wynalazek ułatwiający poranki.','Narysuj wynalazek ułatwiający zasypianie.','Pomyśl o budziku, ubraniu lub śniadaniu.','Pomyśl o świetle, łóżku albo wyciszeniu.'],
['Kreatywne','Narysuj restaurację pod wodą.','Narysuj restaurację w kosmosie.','Pokaż ryby za oknem albo sposób wejścia pod wodę.','Pokaż brak grawitacji albo widok na planety.'],
['Kreatywne','Narysuj buty do zadań specjalnych.','Narysuj plecak do zadań specjalnych.','Dodaj funkcję przydatną podczas biegu lub wspinaczki.','Pokaż, co niezwykłego mieści albo potrafi plecak.'],
['Kreatywne','Narysuj idealny pokój gracza.','Narysuj idealny pokój artysty.','Dodaj ekran, fotel lub nietypowe sterowanie.','Dodaj miejsce na narzędzia, kolory albo dzieła.'],
['Kreatywne','Narysuj maszynę zmieniającą pogodę.','Narysuj maszynę zatrzymującą czas.','Pokaż, jak powstaje słońce, deszcz albo śnieg.','Dodaj zegar, przycisk lub zamrożone przedmioty.'],
['Kreatywne','Narysuj niezwykły tort urodzinowy.','Narysuj niezwykłą pizzę.','Dodaj zaskakujący kształt, piętra lub dekorację.','Dodaj nietypowy kształt albo składniki.'],
['Kreatywne','Narysuj miasto na chmurach.','Narysuj miasto pod ziemią.','Pokaż, jak budynki utrzymują się w powietrzu.','Pokaż tunele, światła albo podziemny transport.'],
['Kreatywne','Narysuj magiczne okulary.','Narysuj magiczny zegarek.','Pokaż, co można przez nie zobaczyć.','Pokaż jego niezwykłą funkcję na tarczy lub pasku.'],
['Kreatywne','Narysuj sport, który jeszcze nie istnieje.','Narysuj instrument, który jeszcze nie istnieje.','Dodaj boisko, sprzęt lub nietypową zasadę.','Pokaż, jak się na nim gra i skąd wydobywa się dźwięk.'],
['Kreatywne','Narysuj statek piratów przyszłości.','Narysuj zamek rycerzy przyszłości.','Połącz żagle i pirackie symbole z technologią.','Połącz wieże i mury z technologią.'],
['Kreatywne','Narysuj potwora, który jest przyjazny.','Narysuj uroczego kosmitę.','Dodaj straszny wygląd i jeden sympatyczny szczegół.','Dodaj nietypowe oczy, czułki albo sposób poruszania.'],
['Kreatywne','Narysuj nietypowy środek transportu do szkoły.','Narysuj nietypowy środek transportu na wakacje.','Pomyśl o szybkim starcie i miejscu na plecak.','Pomyśl o bagażu, wygodzie i dalekiej podróży.'],
['Kreatywne','Narysuj sklep sprzedający marzenia.','Narysuj sklep sprzedający wspomnienia.','Pokaż, jak wyglądają marzenia na półkach.','Pokaż, w czym przechowuje się wspomnienia.'],
['Kreatywne','Narysuj urządzenie do rozmowy ze zwierzętami.','Narysuj urządzenie do rozmowy z roślinami.','Dodaj mikrofon, tłumacz lub ekran z odpowiedzią.','Pokaż, jak roślina przekazuje swoją wiadomość.'],
['Sport','Jaki sport najbardziej lubisz oglądać?','Jaki sport najbardziej lubisz uprawiać?'],['Sport','Który piłkarz jest twoim ulubionym?','Który piłkarz jest najbardziej przereklamowany?'],['Sport','Jaki klub piłkarski ma najlepszych kibiców?','Jaki klub piłkarski ma najładniejsze stroje?'],['Sport','Która reprezentacja wygra najbliższy wielki turniej?','Której reprezentacji najbardziej lubisz kibicować?'],['Sport','Jaki wynik meczu piłkarskiego jest najciekawszy?','Jaki wynik meczu piłkarskiego jest najbardziej bolesny?'],
['Sport','Który sportowiec jest największą legendą?','Z którym sportowcem chciałbyś porozmawiać?'],['Sport','Jaka dyscyplina wymaga najlepszej kondycji?','Jaka dyscyplina wymaga największej precyzji?'],['Sport','Który sport jest najtrudniejszy do nauczenia?','Który sport najłatwiej zacząć uprawiać?'],['Sport','Ile razy w tygodniu warto trenować?','Ile minut powinien trwać dobry trening?'],['Sport','Co najlepiej motywuje do treningu?','Co najczęściej zniechęca do treningu?'],
['Sport','Jaka pora dnia jest najlepsza na trening?','Jaka pogoda jest najlepsza do treningu na zewnątrz?'],['Sport','Które ćwiczenie najbardziej lubisz?','Którego ćwiczenia najbardziej nie lubisz?'],['Sport','Jaki sport najlepiej uprawiać latem?','Jaki sport najlepiej uprawiać zimą?'],['Sport','Która dyscyplina olimpijska jest najciekawsza?','Jakiej dyscypliny brakuje na igrzyskach?'],['Sport','Jaki sport ekstremalny chciałbyś spróbować?','Jakiego sportu ekstremalnego nigdy byś nie spróbował?'],
['Sport','Na jaki mecz chciałbyś dostać bilet?','Na jakie zawody chciałbyś pojechać jako kibic?'],['Sport','Jaki stadion robi największe wrażenie?','Na jakim stadionie chciałbyś zagrać?'],['Sport','Który sport najlepiej nadaje się do gry ze znajomymi?','Który sport najlepiej uprawiać samemu?'],['Sport','Co jest ważniejsze w sporcie: talent czy trening?','Co jest ważniejsze w drużynie: atak czy obrona?'],['Sport','Jaki moment sportowy pamiętasz najlepiej?','Jakie sportowe zwycięstwo chciałbyś zobaczyć na żywo?'],
['Gry','Jaka mechanika w grach daje najwięcej frajdy?','Jaka mechanika w grach najbardziej przeszkadza?'],['Gry','Która gra ma najlepszą muzykę?','Która gra ma najlepsze efekty dźwiękowe?'],['Gry','Jaki otwarty świat chciałbyś odwiedzić?','W jakiej liniowej przygodzie chciałbyś uczestniczyć?'],['Gry','Na jakim poziomie trudności zwykle grasz?','Jaki poziom trudności daje najwięcej satysfakcji?'],['Gry','Jaka gra kooperacyjna jest najlepsza?','Jaka gra rywalizacyjna jest najlepsza?'],
['Gry','Który czarny charakter z gry jest najlepszy?','Który pomocnik z gry jest najlepszy?'],['Gry','Wolisz grać na komputerze czy konsoli?','Wolisz grać na padzie czy klawiaturze?'],['Gry','Co jest ważniejsze w grze: grafika czy fabuła?','Co jest ważniejsze w grze: sterowanie czy muzyka?'],['Gry','Która gra zasługuje na remake?','Która gra zasługuje na kontynuację?'],['Gry','Jaki przedmiot z gry chciałbyś mieć naprawdę?','Jaką umiejętność z gry chciałbyś mieć naprawdę?'],
['Samochody','Jakie klasyczne auto wygląda najlepiej?','Jakie nowoczesne auto wygląda najlepiej?'],['Samochody','Jakie auto wybrałbyś na długą podróż?','Jakie auto wybrałbyś do miasta?'],['Samochody','Jaka funkcja w aucie jest najbardziej przydatna?','Jaka funkcja w aucie jest najbardziej zbędna?'],['Samochody','Wolisz skrzynię manualną czy automatyczną?','Wolisz napęd na przód czy na tył?'],['Samochody','Które auto najlepiej brzmi?','Które auto jest najwygodniejsze?'],['Samochody','Jakim autem chciałbyś pojechać na tor?','Jakim autem chciałbyś pojechać w teren?'],['Samochody','Co ważniejsze w aucie: wygląd czy osiągi?','Co ważniejsze w aucie: wygoda czy spalanie?'],
['Jedzenie','Jaki składnik powinien znaleźć się na idealnej pizzy?','Jaki składnik powinien znaleźć się w idealnym burgerze?'],['Jedzenie','Która kuchnia świata jest najlepsza?','Której kuchni świata najbardziej chcesz spróbować?'],['Jedzenie','Wolisz potrawy ostre czy łagodne?','Wolisz przekąski słodkie czy słone?'],['Jedzenie','Co najlepiej chrupać podczas filmu?','Co najlepiej zjeść podczas meczu?'],['Jedzenie','Jaki gorący napój wybierasz najczęściej?','Jaki zimny napój wybierasz najczęściej?'],['Jedzenie','Wolisz dobrą restaurację czy jedzenie uliczne?','Wolisz bufet czy zamawianie z menu?'],['Jedzenie','Bez jakiego składnika trudno byłoby ci gotować?','Którego składnika prawie nigdy nie używasz?'],
['Zwierzęta','Które zwierzę jest najszybsze?','Które zwierzę jest najsilniejsze?'],['Zwierzęta','Jakie zwierzę morskie jest najciekawsze?','Jakie zwierzę leśne jest najciekawsze?'],['Zwierzęta','Który odgłos zwierzęcia rozpoznasz od razu?','Który odgłos zwierzęcia jest najdziwniejszy?'],['Zwierzęta','Które wymarłe zwierzę chciałbyś zobaczyć?','Które wymarłe zwierzę wyglądało najgroźniej?'],['Zwierzęta','Które zwierzę jest najbardziej inteligentne?','Które zwierzę najlepiej współpracuje w grupie?'],['Zwierzęta','Który ptak wygląda najładniej?','Który ptak lata najbardziej imponująco?'],['Zwierzęta','Który owad jest najbardziej pożyteczny?','Który owad jest najbardziej irytujący?'],
['Codzienne','Co najbardziej lubisz robić w weekend?','Co najbardziej lubisz robić po pracy lub szkole?'],['Codzienne','Którego obowiązku domowego najbardziej nie lubisz?','Który obowiązek domowy wykonujesz najszybciej?'],['Codzienne','Czym najchętniej dojeżdżasz?','Jak chciałbyś dojeżdżać w przyszłości?'],['Codzienne','Jaka pogoda poprawia ci humor?','Jaka pogoda najlepiej pasuje do odpoczynku?'],['Codzienne','Jaki dobry nawyk chciałbyś wyrobić?','Z jakiego złego nawyku chciałbyś zrezygnować?'],['Codzienne','W którym pomieszczeniu spędzasz najwięcej czasu?','Które pomieszczenie urządziłbyś od nowa?'],['Codzienne','Co ostatnio kupiłeś bez planu?','Na co najdłużej odkładasz pieniądze?'],
['Internet','Która sieć społecznościowa jest najciekawsza?','Która sieć społecznościowa zabiera najwięcej czasu?'],['Internet','Jaki rodzaj filmów oglądasz najczęściej?','Jaki rodzaj filmów najczęściej pomijasz?'],['Internet','Którego emoji używasz najczęściej?','Którego emoji nigdy nie rozumiesz?'],['Internet','Jaka strona internetowa jest najbardziej przydatna?','Jaka strona internetowa najlepiej zabija nudę?'],['Internet','Które powiadomienia sprawdzasz od razu?','Które powiadomienia najczęściej ignorujesz?'],['Internet','Czego ostatnio nauczyłeś się z internetu?','Czego chciałbyś nauczyć się z poradnika online?'],
['Losowe','Do jakiej epoki chciałbyś się przenieść?','Który moment z przyszłości chciałbyś zobaczyć?'],['Losowe','Jaki wynalazek najbardziej zmienił świat?','Jakiego wynalazku najbardziej dziś brakuje?'],['Losowe','Jaki talent chciałbyś dostać od razu?','Jaki talent chciałbyś rozwijać przez rok?'],['Losowe','Która pora roku ma najlepszy klimat?','Która pora roku ma najlepsze aktywności?'],['Losowe','Jakie święto lub wydarzenie lubisz najbardziej?','Jakie nowe święto chciałbyś ustanowić?'],['Losowe','Który przedmiot codzienny powinien umieć mówić?','Który przedmiot codzienny powinien poruszać się sam?'],
['Muzyka','Jakiego instrumentu słuchasz najchętniej?','Na jakim instrumencie chciałbyś umieć grać?'],['Muzyka','Na czyj koncert chciałbyś pójść?','Z kim chciałbyś wystąpić na scenie?'],['Muzyka','Który wykonawca ma najlepszy głos?','Który wykonawca ma najlepszy styl?'],['Muzyka','Jaka piosenka poprawia ci humor?','Jaka piosenka pomaga ci się skupić?'],['Muzyka','Który gatunek muzyki pasuje do imprezy?','Który gatunek muzyki pasuje do odpoczynku?'],
['Muzyka','Jaką piosenkę wybrałbyś na karaoke?','Jakiej piosenki nie zaśpiewałbyś na karaoke?'],['Muzyka','Który utwór ma najlepszy początek?','Który utwór ma najlepsze zakończenie?'],['Muzyka','Która okładka albumu wygląda najlepiej?','Jak zaprojektowałbyś własną okładkę albumu?'],['Muzyka','Do jakiej muzyki najlepiej się tańczy?','Przy jakiej muzyce najlepiej się ćwiczy?'],['Muzyka','Która piosenka ma najlepszy tekst?','Która piosenka ma najbardziej chwytliwy refren?'],
['Muzyka','Wolisz muzykę na żywo czy nagraną w studio?','Wolisz koncert w klubie czy na stadionie?'],['Muzyka','Wolisz słuchać muzyki na słuchawkach czy głośnikach?','Wolisz słuchać głośno czy cicho?'],['Muzyka','Z której dekady pochodzi najlepsza muzyka?','W której dekadzie chciałbyś zobaczyć koncert?'],['Muzyka','Który film ma najlepszą muzykę?','Która gra ma najlepszą ścieżkę dźwiękową?'],['Muzyka','Na jaki festiwal muzyczny chciałbyś pojechać?','Jak wyglądałby twój własny festiwal muzyczny?'],
['Muzyka','Który instrument brzmi najpotężniej?','Który instrument brzmi najdelikatniej?'],['Muzyka','Wolisz niski czy wysoki głos?','Wolisz śpiew solowy czy chór?'],['Muzyka','Co jest ważniejsze: rytm czy melodia?','Co jest ważniejsze: tekst czy brzmienie?'],['Muzyka','Jaką piosenkę ustawiłbyś jako budzik?','Jaką piosenkę ustawiłbyś jako dzwonek telefonu?'],['Muzyka','Którzy dwaj artyści powinni nagrać wspólny utwór?','Który artysta powinien spróbować innego gatunku?'],
['Filmy i seriale','Jaki gatunek filmowy wybierasz najczęściej?','Jaki gatunek serialu wybierasz najczęściej?'],['Filmy i seriale','Który filmowy bohater jest najlepszy?','Który serialowy bohater jest najlepszy?'],['Filmy i seriale','Który złoczyńca filmowy jest najciekawszy?','Który złoczyńca najbardziej przeraża?'],['Filmy i seriale','W świecie którego filmu chciałbyś zamieszkać?','W świecie którego serialu chciałbyś zamieszkać?'],['Filmy i seriale','Który film zasługuje na remake?','Którego filmu nigdy nie powinno się przerabiać?'],
['Filmy i seriale','Który film powinien dostać kontynuację?','Który serial powinien dostać dodatkowy sezon?'],['Filmy i seriale','Który aktor najlepiej pasuje do komedii?','Który aktor najlepiej pasuje do filmu akcji?'],['Filmy i seriale','Co najlepiej jeść w kinie?','Co najlepiej pić podczas oglądania filmu?'],['Filmy i seriale','Którą scenę filmową pamiętasz najlepiej?','Które zakończenie filmu pamiętasz najlepiej?'],['Filmy i seriale','Która animacja jest najlepsza dla dorosłych?','Która animacja jest najlepsza dla dzieci?'],
['Filmy i seriale','Ile odcinków powinien mieć dobry serial?','Ile minut powinien trwać dobry odcinek?'],['Filmy i seriale','Wolisz szczęśliwe czy zaskakujące zakończenia?','Wolisz otwarte czy dokładnie wyjaśnione zakończenia?'],['Filmy i seriale','Która komedia śmieszy cię najbardziej?','Który film poprawia ci humor?'],['Filmy i seriale','Który horror jest najstraszniejszy?','Jaki potwór filmowy jest najstraszniejszy?'],['Filmy i seriale','Która technologia z filmu science fiction powinna istnieć?','Który pojazd z filmu science fiction chciałbyś mieć?'],
['Filmy i seriale','Który kostium filmowy wygląda najlepiej?','Który rekwizyt filmowy chciałbyś mieć?'],['Filmy i seriale','W jakim miejscu nakręciłbyś film?','W jakim mieście osadziłbyś serial?'],['Filmy i seriale','Jaki serial najlepiej oglądać po jednym odcinku?','Jaki serial najlepiej obejrzeć w jeden weekend?'],['Filmy i seriale','Która książka została najlepiej zekranizowana?','Która gra powinna dostać ekranizację?'],['Filmy i seriale','Wolisz kino czy oglądanie w domu?','Wolisz film z napisami czy z dubbingiem?'],
['Podróże','Do jakiego kraju chciałbyś pojechać?','W jakim kraju chciałbyś zostać na miesiąc?'],['Podróże','Które miasto najbardziej chcesz odwiedzić?','W którym mieście chciałbyś spędzić weekend?'],['Podróże','Wolisz wakacje nad morzem czy w górach?','Wolisz odpoczynek nad jeziorem czy w lesie?'],['Podróże','Czym najlepiej podróżować na daleką trasę?','Czym najlepiej zwiedzać duże miasto?'],['Podróże','Co zawsze zabierasz w podróż?','Czego najczęściej zapominasz spakować?'],
['Podróże','Wolisz hotel czy domek?','Wolisz namiot czy kampera?'],['Podróże','Jaką trasę wybrałbyś na podróż samochodem?','Jaką trasę wybrałbyś na podróż pociągiem?'],['Podróże','Co robisz podczas długiego lotu?','Co robisz podczas długiej jazdy pociągiem?'],['Podróże','Jakiego jedzenia próbujesz podczas podróży?','Jaki napój kojarzy ci się z wakacjami?'],['Podróże','Co najchętniej fotografujesz na wyjeździe?','Jaką pamiątkę najchętniej przywozisz?'],
['Podróże','Jaka pora roku jest najlepsza na zwiedzanie?','Jaka pora roku jest najlepsza na odpoczynek?'],['Podróże','Z kim najlepiej ci się podróżuje?','Z jaką znaną osobą chciałbyś pojechać w podróż?'],['Podróże','Wolisz podróż zaplanowaną czy spontaniczną?','Wolisz jeden długi wyjazd czy kilka krótkich?'],['Podróże','Który zabytek chcesz zobaczyć na żywo?','Który cud natury chcesz zobaczyć na żywo?'],['Podróże','Na jakiej wyspie chciałbyś spędzić tydzień?','Na jakiej wyspie chciałbyś przeżyć przygodę?'],
['Podróże','Dokąd pojechałbyś tylko na jeden dzień?','Dokąd pojechałbyś na całe lato?'],['Podróże','Jaka pogoda jest idealna na zwiedzanie?','Jaka pogoda jest idealna na plażę?'],['Podróże','Czego chciałbyś spróbować na wakacjach?','Czego chciałbyś nauczyć się podczas podróży?'],['Podróże','Które miejsce odwiedziłbyś ponownie?','Które miejsce wygląda lepiej na zdjęciach niż na żywo?'],['Podróże','Wolisz odkrywać popularne czy mało znane miejsca?','Wolisz zwiedzać rano czy wieczorem?'],
['Szkoła i praca','Który przedmiot szkolny lubisz najbardziej?','Który przedmiot szkolny jest najbardziej przydatny?'],['Szkoła i praca','Jaki powinien być idealny nauczyciel?','Jaki powinien być idealny szef?'],['Szkoła i praca','Jak wyglądałaby idealna lekcja?','Jak wyglądałoby idealne szkolenie w pracy?'],['Szkoła i praca','Co najlepiej robić podczas przerwy?','Jak długa powinna być idealna przerwa?'],['Szkoła i praca','Który rodzaj sprawdzianu jest najłatwiejszy?','Który rodzaj zadania najlepiej sprawdza wiedzę?'],
['Szkoła i praca','Kiedy najlepiej odrabiać zadania?','Gdzie najlepiej się uczyć?'],['Szkoła i praca','Jaki przedmiot zawsze masz na biurku?','Jaki przedmiot zawsze nosisz w plecaku?'],['Szkoła i praca','Jak wyglądałoby twoje idealne biurko?','Jak wyglądałaby twoja idealna sala lekcyjna?'],['Szkoła i praca','Wolisz pracę zdalną czy na miejscu?','Wolisz naukę online czy w klasie?'],['Szkoła i praca','Wolisz pracować samemu czy w zespole?','Wolisz uczyć się samemu czy z kimś?'],
['Szkoła i praca','Co pomaga ci dobrze zacząć dzień pracy?','Co pomaga ci dobrze zacząć dzień w szkole?'],['Szkoła i praca','Jaki zawód chciałbyś wykonywać przez tydzień?','Jakiego zawodu chciałbyś spróbować przez jeden dzień?'],['Szkoła i praca','Jaki dodatek najbardziej poprawiłby biuro?','Jaki dodatek najbardziej poprawiłby szkołę?'],['Szkoła i praca','Jak powinno wyglądać dobre spotkanie?','Jak powinna wyglądać dobra prezentacja?'],['Szkoła i praca','Która umiejętność najbardziej przydaje się w pracy?','Która umiejętność najbardziej przydaje się w szkole?'],
['Szkoła i praca','Co najlepiej zjeść na przerwie?','Co najlepiej zabrać na drugie śniadanie?'],['Szkoła i praca','Jak radzisz sobie z krótkim terminem?','Jak radzisz sobie z trudnym zadaniem?'],['Szkoła i praca','Jak wspominasz swój pierwszy dzień w szkole?','Jak wyobrażasz sobie pierwszy dzień w nowej pracy?'],['Szkoła i praca','Jak powinien wyglądać wygodny strój do pracy?','Jak powinien wyglądać wygodny strój do szkoły?'],['Szkoła i praca','Nad jakim projektem chciałbyś pracować?','Jakiego projektu chciałbyś nauczyć się od podstaw?'],
['Technologia','Jaka funkcja telefonu jest najbardziej przydatna?','Jaka funkcja telefonu jest najbardziej zbędna?'],['Technologia','Który element komputera ulepszyłbyś jako pierwszy?','Który element komputera jest dla ciebie najważniejszy?'],['Technologia','Jaki gadżet elektroniczny nosisz najczęściej?','Jaki gadżet elektroniczny chciałbyś kupić?'],['Technologia','Jakiego robota chciałbyś mieć w domu?','Jakiego robota chciałbyś zobaczyć w mieście?'],['Technologia','Do czego najchętniej używasz sztucznej inteligencji?','Czego sztuczna inteligencja nie powinna robić?'],
['Technologia','Które urządzenie powinno być inteligentne?','Które urządzenie nie potrzebuje połączenia z internetem?'],['Technologia','Za jaką starą technologią tęsknisz?','Która stara technologia powinna wrócić?'],['Technologia','Co chciałbyś zobaczyć w wirtualnej rzeczywistości?','W jaką aktywność spróbowałbyś zagrać w VR?'],['Technologia','Które urządzenie powinno mieć lepszą baterię?','Które urządzenie najczęściej zapominasz naładować?'],['Technologia','Wolisz klawiaturę czy ekran dotykowy?','Wolisz sterowanie głosem czy gestami?'],
['Technologia','Jak będzie wyglądał telefon przyszłości?','Jak będzie wyglądał komputer przyszłości?'],['Technologia','Jak najlepiej chronić swoje konto?','Które dane najbardziej warto zabezpieczać?'],['Technologia','Co najczęściej fotografujesz telefonem?','Jaka funkcja aparatu jest najważniejsza?'],['Technologia','Które powiadomienia są naprawdę potrzebne?','Które urządzenie wysyła za dużo powiadomień?'],['Technologia','Jaki wynalazek ostatnich lat jest najlepszy?','Jaki wynalazek może zmienić najbliższe lata?'],
['Technologia','Które urządzenie najłatwiej naprawić samemu?','Które urządzenie psuje się w najgorszym momencie?'],['Technologia','Jaka aplikacja powinna działać bez internetu?','Jaka usługa internetowa jest najbardziej przydatna?'],['Technologia','Jaki sprzęt ubieralny chciałbyś mieć?','Jaką funkcję powinien mieć idealny zegarek?'],['Technologia','Które urządzenie zabrałbyś na bezludną wyspę?','Które urządzenie najbardziej ułatwia podróż?'],['Technologia','Jakiej technologii będziemy używać za dziesięć lat?','Która dzisiejsza technologia zniknie za dziesięć lat?']];
export const QUESTIONS:QuestionPair[]=pairs.map(([category,questionA,questionB,hintA,hintB],index)=>({id:index+1,category,questionA,questionB,hintA,hintB}));
export const CATEGORIES:CategoryFilter[]=['Wszystkie','CS2','Gry','Samochody','Jedzenie','Zwierzęta','Codzienne','Internet','Losowe','Sport','Kreatywne','Muzyka','Filmy i seriale','Podróże','Szkoła i praca','Technologia'];
export function toggleCategory(current:CategoryFilter[],category:CategoryFilter):CategoryFilter[]{
  if(category==='Wszystkie')return current.length===1&&current[0]==='Wszystkie'?[]:['Wszystkie'];
  const specific=current.filter(value=>value!=='Wszystkie');
  return specific.includes(category)?specific.filter(value=>value!==category):[...specific,category];
}
export function shuffle<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
const THEMES:Array<[string,RegExp]>=[
  ['mapy',/map|bombsite/],['uzbrojenie',/broń|broni|pistolet|nóż|noża|skin/],['granaty',/granat|smoke/],['wynik',/wynik|rund przewagi|rund straty/],['czas',/godzin|czasu potrzebujesz|minut/],
  ['trening',/trening|ćwiczeni|kondycj/],['piłka-nożna',/piłkarz|klub piłkarski|reprezentacj|mecz piłkarski|stadion/],['internet',/aplikacj|internet|online/],['jedzenie',/jedzeni|potraw|lodów/]
];
function questionTheme(question:QuestionPair):string{const text=`${question.questionA} ${question.questionB}`.toLocaleLowerCase('pl'),theme=THEMES.find(([,pattern])=>pattern.test(text))?.[0];return theme?`${question.category}:${theme}`:`pytanie-${question.id}`}
export function areQuestionsSimilar(first:QuestionPair,second:QuestionPair):boolean{return first.id===second.id||questionTheme(first)===questionTheme(second)}
function spreadSimilarQuestions(items:QuestionPair[]):QuestionPair[]{
  const groups=new Map<string,QuestionPair[]>();
  for(const question of shuffle(items)){const theme=questionTheme(question);groups.set(theme,[...(groups.get(theme)??[]),question])}
  const result:QuestionPair[]=[];let previous='';
  while([...groups.values()].some(group=>group.length)){
    const candidates=shuffle([...groups.entries()].filter(([theme,group])=>group.length&&theme!==previous)).sort((a,b)=>b[1].length-a[1].length);
    const selected=candidates[0]??[...groups.entries()].find(([,group])=>group.length)!;
    result.push(selected[1].pop()!);previous=selected[0];
  }
  return result;
}
export function buildQuestionDeck(items:QuestionPair[],balanceCategories=false):number[]{
  if(!balanceCategories)return spreadSimilarQuestions(items).map(question=>question.id);
  const groups=new Map<Category,QuestionPair[]>();
  for(const question of items)groups.set(question.category,[...(groups.get(question.category)??[]),question]);
  const categories=shuffle([...groups.keys()]),queues=new Map(categories.map(category=>[category,spreadSimilarQuestions(groups.get(category)??[])])),deck:number[]=[];
  while([...queues.values()].some(queue=>queue.length))for(const category of categories){const question=queues.get(category)?.shift();if(question)deck.push(question.id)}
  return deck;
}
export function prepareQuestionCycle(items:QuestionPair[],usedIds:number[],minimumRemaining=1):{items:QuestionPair[];usedIds:number[]}{
  const used=new Set(usedIds),unused=items.filter(question=>!used.has(question.id));
  if(unused.length>=minimumRemaining)return{items:unused,usedIds};
  const poolIds=new Set(items.map(question=>question.id));
  return{items,usedIds:usedIds.filter(id=>!poolIds.has(id))};
}
