export type Category='CS2'|'Gry'|'Samochody'|'Jedzenie'|'Zwierzęta'|'Codzienne'|'Internet'|'Losowe'|'Sport'|'Kreatywne';
export type CategoryFilter=Category|'Wszystkie';
export interface QuestionPair{id:number;questionA:string;questionB:string;category:Category;hintA?:string;hintB?:string}
const pairs:Array<[Category,string,string,string?,string?]>=[
['CS2','Jaka jest twoja ulubiona mapa w CS2?','Jaka jest najgorsza mapa w CS2?'],['CS2','Jaką broń kupujesz najczęściej?','Jaką broń najczęściej podnosisz po przeciwniku?'],['CS2','Ile fragów to dla ciebie dobry mecz?','Ile fragów zwykle robisz?'],['CS2','Którą mapę znasz najlepiej?','Na której mapie najczęściej się gubisz?'],['CS2','Jaka broń najlepiej wygląda?','Jaka broń najlepiej brzmi?'],
['CS2','Na którym bombsite wolisz grać?','Którego bombsite najtrudniej ci odbić?'],['CS2','Którą pozycję najczęściej zajmujesz?','Której pozycji najbardziej nie lubisz pilnować?'],['CS2','Jaki granat kupujesz najczęściej?','O jakim granacie najczęściej zapominasz?'],['CS2','Z kim najlepiej gra ci się w drużynie?','Kto najbardziej rozprasza cię podczas gry?'],['CS2','Jaki skin chciałbyś mieć?','Jaki skin sprzedałbyś jako pierwszy?'],
['CS2','Ile rund przewagi daje ci spokój?','Przy ilu rundach straty tracisz nadzieję?'],['CS2','Który pistolet wybierasz?','Z którym pistoletem radzisz sobie najgorzej?'],['CS2','Jakiego pro gracza oglądasz najchętniej?','Z jakim pro graczem chciałbyś zagrać?'],['CS2','Co kupujesz po wygranej pistoletówce?','Co kupujesz, gdy brakuje pieniędzy?'],['CS2','Jaką rolę lubisz grać?','Jakiej roli unikasz?'],
['CS2','Gdzie najczęściej rzucasz smoke?','Gdzie najbardziej przeszkadza ci smoke?'],['CS2','Jaki wynik uznajesz za bliski?','Przy jakim wyniku mecz jest już przegrany?'],['CS2','Ile godzin tygodniowo grasz?','Ile godzin tygodniowo oglądasz CS2?'],['CS2','Która mapa ma najlepszy klimat?','Która mapa ma najgorszą widoczność?'],['CS2','Jaką broń wybierasz na daleki dystans?','Jaką broń wybierasz na bliski dystans?'],
['CS2','Kiedy najczęściej robisz eco?','Kiedy najczęściej robisz force buy?'],['CS2','Co najczęściej krzyczysz po wygranej?','Co robisz po przegranej rundzie?'],['CS2','Jaki nóż chciałbyś wylosować?','Jakiego noża nie chciałbyś dostać?'],['CS2','Ile czasu potrzebujesz na rozgrzewkę?','Po ilu meczach robisz przerwę?'],['CS2','Który tryb gry wybierasz najczęściej?','Którego trybu prawie nie używasz?'],
['CS2','Co najlepiej poprawia twoją celność?','Co najbardziej psuje twoją celność?'],['CS2','Na której mapie najlepiej grasz jako CT?','Na której mapie najlepiej grasz jako T?'],['CS2','Jaki nick zapamiętałeś najbardziej?','Jaki nick ustawiłbyś sobie dziś?'],['CS2','Który dźwięk w grze rozpoznajesz od razu?','Który dźwięk najczęściej ignorujesz?'],['CS2','Co robisz przed meczem rankingowym?','Co robisz zaraz po meczu rankingowym?'],
['Gry','W jaką grę możesz grać cały dzień?','Jaką grę najchętniej obejrzysz u kogoś?'],['Gry','Jaka gra była twoją pierwszą?','Jaką grę ostatnio uruchomiłeś?'],['Gry','Która postać z gry jest najlepsza?','Która postać z gry najbardziej cię denerwuje?'],['Gry','Na jakiej konsoli chciałbyś grać?','Jaką konsolę miałeś jako pierwszą?'],['Gry','Jaka gra najlepiej nadaje się na imprezę?','Jaka gra najlepiej nadaje się do grania samemu?'],
['Samochody','Jakim autem chciałbyś jeździć na co dzień?','Jakim autem chciałbyś przejechać się tylko raz?'],['Samochody','Jaki kolor auta wybrałbyś dla siebie?','Jaki kolor auta najłatwiej zauważyć?'],['Samochody','Jaka marka wygląda najlepiej?','Jaka marka jest najbardziej praktyczna?'],['Samochody','Ile powinno kosztować dobre auto?','Ile wydałbyś na pierwsze auto?'],['Samochody','Gdzie pojechałbyś samochodem?','Gdzie nigdy nie chciałbyś prowadzić?'],
['Jedzenie','Jakie jedzenie zamawiasz najczęściej?','Jakie jedzenie najchętniej przygotowałbyś sam?'],['Jedzenie','Co najlepiej jeść rano?','Co najlepiej jeść późnym wieczorem?'],['Jedzenie','Jaki smak lodów wybierasz?','Jakiego smaku lodów nigdy nie wybierasz?'],['Jedzenie','Co kupujesz na imprezę?','Co zabierasz na piknik?'],['Jedzenie','Jaka potrawa kojarzy ci się z domem?','Jaką potrawę chciałbyś spróbować za granicą?'],
['Zwierzęta','Jakim zwierzęciem chciałbyś być?','Jakie zwierzę najbardziej cię wkurza?'],['Zwierzęta','Jakie zwierzę jest najsłodsze?','Jakie zwierzę jest najstraszniejsze?'],['Zwierzęta','Jakie zwierzę chciałbyś mieć?','Jakiego zwierzęcia nie wpuściłbyś do domu?'],['Zwierzęta','Które zwierzę najlepiej pływa?','Które zwierzę najlepiej biega?'],['Zwierzęta','Jakie zwierzę kojarzy ci się z tobą?','Jakie zwierzę kojarzy ci się z twoim sąsiadem?'],
['Codzienne','O której zwykle wstajesz?','O której zwykle zasypiasz?'],['Codzienne','Co robisz zaraz po obudzeniu?','Co robisz tuż przed snem?'],['Codzienne','Ile czasu zajmuje ci wyjście z domu?','Ile czasu zajmuje ci powrót do formy po imprezie?'],['Codzienne','Co najczęściej nosisz w kieszeni?','Co najczęściej zostawiasz w domu?'],['Codzienne','Gdzie odpoczywasz najlepiej?','Gdzie najłatwiej ci zasnąć?'],
['Internet','Jakiej aplikacji używasz najczęściej?','Którą aplikację najchętniej byś usunął?'],['Internet','Kogo najchętniej oglądasz w internecie?','Z kim chciałbyś nagrać film?'],['Internet','Jaki mem zawsze cię śmieszy?','Jaki mem znudził ci się najbardziej?'],['Internet','Ile czasu spędzasz dziennie online?','Ile czasu wytrzymasz bez internetu?'],['Internet','Co najczęściej wyszukujesz?','Czego nigdy nie wpisałbyś publicznie?'],
['Losowe','Co zabrałbyś na bezludną wyspę?','Co zabrałbyś na koniec świata?'],['Losowe','Jaki superpower chciałbyś mieć?','Jaki superpower byłby najbardziej bezużyteczny?'],['Losowe','Gdzie chciałbyś mieszkać?','Gdzie chciałbyś pojechać tylko raz?'],['Losowe','Co kupiłbyś za milion złotych?','Co kupiłbyś za ostatnie sto złotych?'],['Losowe','Kim chciałeś zostać jako dziecko?','Kim chciałbyś być przez jeden dzień?'],
['Kreatywne','Narysuj pojazd z przyszłości.','Narysuj dom z przyszłości.','Pomyśl o niezwykłym napędzie, kołach albo skrzydłach.','Dodaj element, którego nie ma w dzisiejszych domach.'],
['Kreatywne','Narysuj nowe zwierzę.','Narysuj nową roślinę.','Połącz cechy dwóch znanych zwierząt.','Wymyśl kształt, liście lub owoce, których jeszcze nie ma.'],
['Kreatywne','Narysuj robota do sprzątania.','Narysuj robota do gotowania.','Pokaż narzędzie, którym robot usuwa bałagan.','Pokaż, jak robot przygotowuje albo podaje jedzenie.'],
['Kreatywne','Narysuj najdziwniejszy plac zabaw.','Narysuj najdziwniejszą szkołę.','Zmień huśtawkę, zjeżdżalnię lub karuzelę.','Zmień salę lekcyjną, ławki albo tablicę.'],
['Kreatywne','Narysuj superbohatera z zabawną mocą.','Narysuj złoczyńcę z zabawną mocą.','Pokaż moc za pomocą stroju lub rekwizytu.','Pokaż, czym postać próbuje przeszkodzić innym.'],
['Kreatywne','Narysuj wyspę marzeń.','Narysuj planetę marzeń.','Dodaj miejsce do odpoczynku i jedną atrakcję.','Pokaż nietypowy krajobraz albo mieszkańców.'],
['Kreatywne','Narysuj wynalazek ułatwiający poranki.','Narysuj wynalazek ułatwiający zasypianie.','Pomyśl o budziku, ubraniu lub śniadaniu.','Pomyśl o świetle, łóżku albo wyciszeniu.'],
['Kreatywne','Narysuj restaurację pod wodą.','Narysuj restaurację w kosmosie.','Pokaż ryby za oknem albo sposób wejścia pod wodę.','Pokaż brak grawitacji albo widok na planety.'],
['Kreatywne','Narysuj buty do zadań specjalnych.','Narysuj plecak do zadań specjalnych.','Dodaj funkcję przydatną podczas biegu lub wspinaczki.','Pokaż, co niezwykłego mieści albo potrafi plecak.'],
['Kreatywne','Narysuj idealny pokój gracza.','Narysuj idealny pokój artysty.','Dodaj ekran, fotel lub nietypowe sterowanie.','Dodaj miejsce na narzędzia, kolory albo dzieła.'],
['Kreatywne','Narysuj maszynę zmieniającą pogodę.','Narysuj maszynę zatrzymującą czas.','Pokaż, jak powstaje słońce, deszcz albo śnieg.','Dodaj zegar, przycisk lub zamrożone przedmioty.'],
['Kreatywne','Narysuj niezwykły tort urodzinowy.','Narysuj niezwykłą pizzę.','Dodaj zaskakujący kształt, piętra lub dekorację.','Dodaj nietypowy kształt albo składniki.'],
['Kreatywne','Narysuj miasto na chmurach.','Narysuj miasto pod ziemią.','Pokaż, jak budynki utrzymują się w powietrzu.','Pokaż tunele, światła albo podziemny transport.'],
['Kreatywne','Narysuj magiczne okulary.','Narysuj magiczny zegarek.','Pokaż, co można przez nie zobaczyć.','Pokaż jego niezwykłą funkcję na tarczy lub pasku.'],
['Kreatywne','Narysuj sport, który jeszcze nie istnieje.','Narysuj instrument, który jeszcze nie istnieje.','Dodaj boisko, sprzęt lub nietypową zasadę.','Pokaż, jak się na nim gra i skąd wydobywa się dźwięk.'],
['Kreatywne','Narysuj statek piratów przyszłości.','Narysuj zamek rycerzy przyszłości.','Połącz żagle i pirackie symbole z technologią.','Połącz wieże i mury z technologią.'],
['Kreatywne','Narysuj potwora, który jest przyjazny.','Narysuj uroczego kosmitę.','Dodaj straszny wygląd i jeden sympatyczny szczegół.','Dodaj nietypowe oczy, czułki albo sposób poruszania.'],
['Kreatywne','Narysuj nietypowy środek transportu do szkoły.','Narysuj nietypowy środek transportu na wakacje.','Pomyśl o szybkim starcie i miejscu na plecak.','Pomyśl o bagażu, wygodzie i dalekiej podróży.'],
['Kreatywne','Narysuj sklep sprzedający marzenia.','Narysuj sklep sprzedający wspomnienia.','Pokaż, jak wyglądają marzenia na półkach.','Pokaż, w czym przechowuje się wspomnienia.'],
['Kreatywne','Narysuj urządzenie do rozmowy ze zwierzętami.','Narysuj urządzenie do rozmowy z roślinami.','Dodaj mikrofon, tłumacz lub ekran z odpowiedzią.','Pokaż, jak roślina przekazuje swoją wiadomość.'],
['Sport','Jaki sport najbardziej lubisz oglądać?','Jaki sport najbardziej lubisz uprawiać?'],['Sport','Który piłkarz jest twoim ulubionym?','Który piłkarz jest najbardziej przereklamowany?'],['Sport','Jaki klub piłkarski ma najlepszych kibiców?','Jaki klub piłkarski ma najładniejsze stroje?'],['Sport','Która reprezentacja wygra najbliższy wielki turniej?','Której reprezentacji najbardziej lubisz kibicować?'],['Sport','Jaki wynik meczu piłkarskiego jest najciekawszy?','Jaki wynik meczu piłkarskiego jest najbardziej bolesny?'],
['Sport','Który sportowiec jest największą legendą?','Z którym sportowcem chciałbyś porozmawiać?'],['Sport','Jaka dyscyplina wymaga najlepszej kondycji?','Jaka dyscyplina wymaga największej precyzji?'],['Sport','Który sport jest najtrudniejszy do nauczenia?','Który sport najłatwiej zacząć uprawiać?'],['Sport','Ile razy w tygodniu warto trenować?','Ile minut powinien trwać dobry trening?'],['Sport','Co najlepiej motywuje do treningu?','Co najczęściej zniechęca do treningu?'],
['Sport','Jaka pora dnia jest najlepsza na trening?','Jaka pogoda jest najlepsza do treningu na zewnątrz?'],['Sport','Które ćwiczenie najbardziej lubisz?','Którego ćwiczenia najbardziej nie lubisz?'],['Sport','Jaki sport najlepiej uprawiać latem?','Jaki sport najlepiej uprawiać zimą?'],['Sport','Która dyscyplina olimpijska jest najciekawsza?','Jakiej dyscypliny brakuje na igrzyskach?'],['Sport','Jaki sport ekstremalny chciałbyś spróbować?','Jakiego sportu ekstremalnego nigdy byś nie spróbował?'],
['Sport','Na jaki mecz chciałbyś dostać bilet?','Na jakie zawody chciałbyś pojechać jako kibic?'],['Sport','Jaki stadion robi największe wrażenie?','Na jakim stadionie chciałbyś zagrać?'],['Sport','Który sport najlepiej nadaje się do gry ze znajomymi?','Który sport najlepiej uprawiać samemu?'],['Sport','Co jest ważniejsze w sporcie: talent czy trening?','Co jest ważniejsze w drużynie: atak czy obrona?'],['Sport','Jaki moment sportowy pamiętasz najlepiej?','Jakie sportowe zwycięstwo chciałbyś zobaczyć na żywo?']];
export const QUESTIONS:QuestionPair[]=pairs.map(([category,questionA,questionB,hintA,hintB],index)=>({id:index+1,category,questionA,questionB,hintA,hintB}));
export const CATEGORIES:CategoryFilter[]=['Wszystkie','CS2','Gry','Samochody','Jedzenie','Zwierzęta','Codzienne','Internet','Losowe','Sport','Kreatywne'];
export function toggleCategory(current:CategoryFilter[],category:CategoryFilter):CategoryFilter[]{
  if(category==='Wszystkie')return current.length===1&&current[0]==='Wszystkie'?[]:['Wszystkie'];
  const specific=current.filter(value=>value!=='Wszystkie');
  return specific.includes(category)?specific.filter(value=>value!==category):[...specific,category];
}
export function shuffle<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
export function buildQuestionDeck(items:QuestionPair[],balanceCategories=false):number[]{
  if(!balanceCategories)return shuffle(items.map(question=>question.id));
  const groups=new Map<Category,QuestionPair[]>();
  for(const question of items)groups.set(question.category,[...(groups.get(question.category)??[]),question]);
  const categories=shuffle([...groups.keys()]),queues=new Map(categories.map(category=>[category,shuffle(groups.get(category)??[])])),deck:number[]=[];
  while([...queues.values()].some(queue=>queue.length))for(const category of categories){const question=queues.get(category)?.shift();if(question)deck.push(question.id)}
  return deck;
}
export function prepareQuestionCycle(items:QuestionPair[],usedIds:number[]):{items:QuestionPair[];usedIds:number[]}{
  const used=new Set(usedIds),unused=items.filter(question=>!used.has(question.id));
  if(unused.length)return{items:unused,usedIds};
  const poolIds=new Set(items.map(question=>question.id));
  return{items,usedIds:usedIds.filter(id=>!poolIds.has(id))};
}
