export type Category='CS2'|'Gry'|'Samochody'|'Jedzenie'|'Zwierzęta'|'Codzienne'|'Internet'|'Losowe';
export interface QuestionPair{id:number;questionA:string;questionB:string;category:Category}
const pairs:Array<[Category,string,string]>=[
['CS2','Jaka jest twoja ulubiona mapa w CS2?','Jaka jest najgorsza mapa w CS2?'],['CS2','Jaką broń kupujesz najczęściej?','Jaką broń najczęściej podnosisz po przeciwniku?'],['CS2','Ile fragów to dla ciebie dobry mecz?','Ile fragów zwykle robisz?'],['CS2','Którą mapę znasz najlepiej?','Na której mapie najczęściej się gubisz?'],['CS2','Jaka broń najlepiej wygląda?','Jaka broń najlepiej brzmi?'],
['CS2','Na którym bombsite wolisz grać?','Którego bombsite najtrudniej ci odbić?'],['CS2','Którą pozycję najczęściej zajmujesz?','Której pozycji najbardziej nie lubisz pilnować?'],['CS2','Jaki granat kupujesz najczęściej?','O jakim granacie najczęściej zapominasz?'],['CS2','Z kim najlepiej gra ci się w drużynie?','Kto najbardziej rozprasza cię podczas gry?'],['CS2','Jaki skin chciałbyś mieć?','Jaki skin sprzedałbyś jako pierwszy?'],
['CS2','Ile rund przewagi daje ci spokój?','Przy ilu rundach straty tracisz nadzieję?'],['CS2','Który pistolet wybierasz?','Z którym pistoletem radzisz sobie najgorzej?'],['CS2','Jakiego pro gracza oglądasz najchętniej?','Z jakim pro graczem chciałbyś zagrać?'],['CS2','Co kupujesz po wygranej pistoletówce?','Co kupujesz, gdy brakuje pieniędzy?'],['CS2','Jaką rolę lubisz grać?','Jakiej roli unikasz?'],
['CS2','Gdzie najczęściej rzucasz smoke?','Gdzie najbardziej przeszkadza ci smoke?'],['CS2','Jaki wynik uznajesz za bliski?','Przy jakim wyniku mecz jest już przegrany?'],['CS2','Ile godzin tygodniowo grasz?','Ile godzin tygodniowo oglądasz CS2?'],['CS2','Która mapa ma najlepszy klimat?','Która mapa ma najgorszą widoczność?'],['CS2','Jaką broń wybierasz na daleki dystans?','Jaką broń wybierasz na bliski dystans?'],
['CS2','Kiedy najczęściej robisz eco?','Kiedy najczęściej robisz force buy?'],['CS2','Co najczęściej krzyczysz po wygranej?','Co robisz po przegranej rundzie?'],['CS2','Jaki nóż chciałbyś wylosować?','Jakiego noża nie chciałbyś dostać?'],['CS2','Ile czasu potrzebujesz na rozgrzewkę?','Po ilu meczach robisz przerwę?'],['CS2','Który tryb gry wybierasz najczęściej?','Którego trybu prawie nie używasz?'],
['CS2','Co najlepiej poprawia twoją celność?','Co najbardziej psuje twoją celność?'],['CS2','Na której mapie najlepiej grasz jako CT?','Na której mapie najlepiej grasz jako T?'],['CS2','Jaki nick zapamiętałeś najbardziej?','Jaki nick ustawiłbyś sobie dziś?'],['CS2','Który dźwięk w grze rozpoznajesz od razu?','Który dźwięk najczęściej ignorujesz?'],['CS2','Co robisz przed meczem rankingowym?','Co robisz zaraz po meczu rankingowym?'],
['Gry','W jaką grę możesz grać cały dzień?','Jaką grę najchętniej obejrzysz u kogoś?'],['Gry','Jaka gra była twoją pierwszą?','Jaką grę ostatnio uruchomiłeś?'],['Gry','Która postać z gry jest najlepsza?','Która postać z gry najbardziej cię denerwuje?'],['Gry','Na jakiej konsoli chciałbyś grać?','Jaką konsolę miałeś jako pierwszą?'],['Gry','Jaka gra najlepiej nadaje się na imprezę?','Jaka gra najlepiej nadaje się do grania samemu?'],
['Samochody','Jakim autem chciałbyś jeździć na co dzień?','Jakim autem chciałbyś przejechać się tylko raz?'],['Samochody','Jaki kolor auta wybrałbyś dla siebie?','Jaki kolor auta najłatwiej zauważyć?'],['Samochody','Jaka marka wygląda najlepiej?','Jaka marka jest najbardziej praktyczna?'],['Samochody','Ile powinno kosztować dobre auto?','Ile wydałbyś na pierwsze auto?'],['Samochody','Gdzie pojechałbyś samochodem?','Gdzie nigdy nie chciałbyś prowadzić?'],
['Jedzenie','Jakie jedzenie zamawiasz najczęściej?','Jakie jedzenie najchętniej przygotowałbyś sam?'],['Jedzenie','Co najlepiej jeść rano?','Co najlepiej jeść późnym wieczorem?'],['Jedzenie','Jaki smak lodów wybierasz?','Jakiego smaku lodów nigdy nie wybierasz?'],['Jedzenie','Co kupujesz na imprezę?','Co zabierasz na piknik?'],['Jedzenie','Jaka potrawa kojarzy ci się z domem?','Jaką potrawę chciałbyś spróbować za granicą?'],
['Zwierzęta','Jakim zwierzęciem chciałbyś być?','Jakie zwierzę najbardziej cię wkurza?'],['Zwierzęta','Jakie zwierzę jest najsłodsze?','Jakie zwierzę jest najstraszniejsze?'],['Zwierzęta','Jakie zwierzę chciałbyś mieć?','Jakiego zwierzęcia nie wpuściłbyś do domu?'],['Zwierzęta','Które zwierzę najlepiej pływa?','Które zwierzę najlepiej biega?'],['Zwierzęta','Jakie zwierzę kojarzy ci się z tobą?','Jakie zwierzę kojarzy ci się z twoim sąsiadem?'],
['Codzienne','O której zwykle wstajesz?','O której zwykle zasypiasz?'],['Codzienne','Co robisz zaraz po obudzeniu?','Co robisz tuż przed snem?'],['Codzienne','Ile czasu zajmuje ci wyjście z domu?','Ile czasu zajmuje ci powrót do formy po imprezie?'],['Codzienne','Co najczęściej nosisz w kieszeni?','Co najczęściej zostawiasz w domu?'],['Codzienne','Gdzie odpoczywasz najlepiej?','Gdzie najłatwiej ci zasnąć?'],
['Internet','Jakiej aplikacji używasz najczęściej?','Którą aplikację najchętniej byś usunął?'],['Internet','Kogo najchętniej oglądasz w internecie?','Z kim chciałbyś nagrać film?'],['Internet','Jaki mem zawsze cię śmieszy?','Jaki mem znudził ci się najbardziej?'],['Internet','Ile czasu spędzasz dziennie online?','Ile czasu wytrzymasz bez internetu?'],['Internet','Co najczęściej wyszukujesz?','Czego nigdy nie wpisałbyś publicznie?'],
['Losowe','Co zabrałbyś na bezludną wyspę?','Co zabrałbyś na koniec świata?'],['Losowe','Jaki superpower chciałbyś mieć?','Jaki superpower byłby najbardziej bezużyteczny?'],['Losowe','Gdzie chciałbyś mieszkać?','Gdzie chciałbyś pojechać tylko raz?'],['Losowe','Co kupiłbyś za milion złotych?','Co kupiłbyś za ostatnie sto złotych?'],['Losowe','Kim chciałeś zostać jako dziecko?','Kim chciałbyś być przez jeden dzień?']];
export const QUESTIONS:QuestionPair[]=pairs.map(([category,questionA,questionB],index)=>({id:index+1,category,questionA,questionB}));
export const CATEGORIES:Category[]=['CS2','Gry','Samochody','Jedzenie','Zwierzęta','Codzienne','Internet','Losowe'];
export function shuffle<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
